title: Marcelo Sanches # your name (or website title) here
logo: "/images/round_profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Science Engineer at KPA. Add a description here.
  <br><br>
  I also do more stuff. See my stuff here on the side.
  <br><br>
  <a href="https://www.linkedin.com/in/big-bang-data/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-midnight
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
